# Generated by Django 3.1.7 on 2021-06-11 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anne', '0002_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='topic_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='topic',
            name='topic_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
