# Generated by Django 3.1.7 on 2021-06-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anne', '0003_auto_20210611_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='topic_file',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
