# Generated by Django 3.1.7 on 2021-06-12 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anne', '0004_auto_20210611_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subject_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
