# Generated by Django 3.1.7 on 2021-06-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anne', '0005_subject_subject_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='topic_file',
            field=models.FileField(upload_to='files/'),
        ),
    ]
