# Generated by Django 3.1.7 on 2021-06-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anne', '0006_auto_20210612_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='topic_file',
        ),
        migrations.AddField(
            model_name='topic',
            name='file',
            field=models.FileField(default=1, max_length=200, upload_to='files/'),
            preserve_default=False,
        ),
    ]
