# Generated by Django 3.1.7 on 2021-06-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anne', '0007_auto_20210612_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
