# Generated by Django 3.1.7 on 2021-07-17 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anne', '0009_auto_20210612_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('topic_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='anne.topic')),
            ],
        ),
    ]
