# Generated by Django 3.1.7 on 2021-07-26 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anne', '0013_auto_20210726_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.CharField(max_length=500),
        ),
    ]
