# Generated by Django 3.1.7 on 2022-02-09 09:58

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('anne', '0014_auto_20210726_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', embed_video.fields.EmbedVideoField()),
                ('desc', models.CharField(default='SOME STRING', max_length=200)),
                ('added', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['-added'],
            },
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='unit_topic',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='unit_subject',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
