# Generated by Django 3.1.7 on 2022-02-11 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anne', '0015_auto_20220209_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteDesc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_desc', models.CharField(default='SOME STRING', max_length=200)),
            ],
        ),
    ]
